package opencode

import (
	"fmt"
	"os"
	"path/filepath"
)

// pluginTemplate is the JavaScript plugin that hooks into OpenCode's
// tool execution hooks and calls shiftlog store after git commits.
//
// OpenCode plugin hooks:
//   tool.execute.before(input, output) — input: {tool, sessionID, callID}, output: {args}
//   tool.execute.after(input, output)  — input: {tool, sessionID, callID}, output: {title, output, metadata}
//
// The command string is only available in the "before" hook (via output.args),
// so we capture it there and act on it in the "after" hook, matching by callID.
const pluginTemplate = `// shiftlog plugin for OpenCode CLI
// Auto-generated by shiftlog init --agent=opencode
// Do not edit manually - re-run 'shiftlog init --agent=opencode' to update

export const ShiftlogPlugin = async (pluginInput) => {
  // Destructure defensively: newer OpenCode releases may invoke the plugin
  // factory with a differently shaped (or missing) input object. A failed
  // destructuring pattern here throws synchronously during plugin load and
  // can block OpenCode from ever starting a session (every future 'run'
  // hangs waiting on plugin initialization), not just this one.
  const directory = (pluginInput && pluginInput.directory) || process.cwd();
  const client = pluginInput && pluginInput.client;

  const pendingCommits = new Map();

  return {
    "tool.execute.before": async (input, output) => {
      try {
        const command = output?.args?.command || output?.args?.cmd || "";
        if (command.includes("git commit") || command.includes("git-commit")) {
          pendingCommits.set(input?.callID, {
            command,
            tool: input?.tool,
            sessionID: input?.sessionID,
          });
        }
      } catch (e) {
        // Never let plugin errors block tool execution
      }
    },

    "tool.execute.after": async (input, output) => {
      try {
        const pending = pendingCommits.get(input?.callID);
        if (!pending) return;
        pendingCommits.delete(input.callID);

        // Try to fetch messages via the SDK client API
        let transcriptData = "";
        if (client && pending.sessionID) {
          try {
            const msgs = await client.session.messages({ path: { id: pending.sessionID } });
            if (msgs && Array.isArray(msgs)) {
              transcriptData = JSON.stringify(msgs.map(m => ({
                role: m.role || "",
                id: m.id || "",
                content: m.content || "",
                time: m.time || {},
              })));
            }
          } catch (e) {
            // Fall back to data_dir approach below
          }
        }

        const dataDir = process.platform === "darwin"
            ? process.env.HOME + "/Library/Application Support/opencode"
            : (process.env.XDG_DATA_HOME || process.env.HOME + "/.local/share") + "/opencode";

        const hookData = JSON.stringify({
          session_id: pending.sessionID || "",
          data_dir: dataDir,
          project_dir: directory,
          tool_name: pending.tool || "",
          tool_input: { command: pending.command },
          ...(transcriptData ? { transcript_data: transcriptData } : {}),
        });

        // Fire-and-forget: do not block OpenCode's hook resolution on our
        // store command finishing. A synchronous execSync call here stalls
        // the plugin runtime for the full duration of the command, and if
        // OpenCode now awaits hook completion before continuing the
        // session, that stall is visible as the whole CLI hanging.
        const { spawn } = await import("child_process");
        const child = spawn("shiftlog", ["store", "--agent=opencode"], {
          cwd: directory,
          stdio: ["pipe", "ignore", "ignore"],
          detached: true,
        });
        child.on("error", () => {});
        child.stdin.on("error", () => {});
        child.stdin.write(hookData);
        child.stdin.end();
        child.unref();
      } catch (e) {
        // Silently ignore errors to not disrupt workflow
      }
    },
  };
};
`

// InstallPlugin writes the shiftlog plugin to .opencode/plugins/shiftlog.js.
func InstallPlugin(repoRoot string) error {
	pluginDir := filepath.Join(repoRoot, ".opencode", "plugins")
	if err := os.MkdirAll(pluginDir, 0755); err != nil {
		return fmt.Errorf("could not create plugin directory: %w", err)
	}

	pluginPath := filepath.Join(pluginDir, "shiftlog.js")
	if err := os.WriteFile(pluginPath, []byte(pluginTemplate), 0644); err != nil {
		return fmt.Errorf("could not write plugin file: %w", err)
	}

	return nil
}

// RemovePlugin removes the shiftlog plugin file.
// Also removes the plugins directory if it's empty afterward.
func RemovePlugin(repoRoot string) error {
	pluginPath := filepath.Join(repoRoot, ".opencode", "plugins", "shiftlog.js")
	if err := os.Remove(pluginPath); err != nil && !os.IsNotExist(err) {
		return err
	}

	// Remove plugins dir if empty
	pluginDir := filepath.Join(repoRoot, ".opencode", "plugins")
	entries, err := os.ReadDir(pluginDir)
	if err == nil && len(entries) == 0 {
		_ = os.Remove(pluginDir)
	}

	return nil
}

// HasPlugin checks if the shiftlog plugin is installed.
func HasPlugin(repoRoot string) bool {
	pluginPath := filepath.Join(repoRoot, ".opencode", "plugins", "shiftlog.js")
	_, err := os.Stat(pluginPath)
	return err == nil
}
